"""update phone

Revision ID: 3d3a3a06b9d6
Revises: 19506bcefa79
Create Date: 2022-07-01 18:31:44.313640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3a3a06b9d6'
down_revision = '19506bcefa79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('phone', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'phone')
    # ### end Alembic commands ###
